set-option -g mouse on

setw -g mode-keys vi
set -g set-clipboard on
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.
# unbind-key -t vi-copy v  # Prior to version 2.4
# unbind-key -T copy-mode-vi v

unbind %
bind v split-window -v
unbind '"'
bind h split-window -h

set-option -g prefix2 M-j

