#!/usr/bin/env sh

# variables
gaps_bar="15"
gaps_normal="15"
gaps_inner="10"

# other app needs float
otherApp='^(提醒事项|备忘录|哔哩哔哩|IINA|Finder|访达|Calendar|System\ Preferences|系统偏好设置|Preview|预览|Mail|WeChat|微信|WeCom|企业微信|PicGo|qv2ray|Corplink|飞连|Plash|Karabiner-Elements|TG\ Pro|Maccy|App\ Store|小鹅通助手)$'
yabai -m rule --add app="${otherApp}" manage=off

# Tiling settings

yabai -m config layout              bsp

# bar settings

yabai -m config top_padding         "${gaps_bar}"
yabai -m config bottom_padding      "${gaps_bar}"
yabai -m config right_padding       "${gaps_normal}"
yabai -m config left_padding        "${gaps_normal}"
yabai -m config window_gap          "${gaps_inner}"

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

skhd -c $HOME/.skhdrc
