metric = "remaining"
style = "rainbow_threshold"
show_title = true
title_template = "❤️ HP {percent}%"
icon_width = 200
color_mode = "threshold"
border_radius = 20
menu_percent_digits = 8

[threshold_boundaries]
lower = 30
upper = 50
